[build-system]
build-backend = "poetry.core.masonry.api"

requires = [ "poetry-core>=2,<3" ]

[project]
name = "url-shorten"
version = "0.2.0"
description = "A simple URL shortener built with Python."
readme = "README.md"
authors = [
  { name = "Karthik Udyawar", email = "karthikajitudy@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "pyperclip>=1.9,<2",
  "pyshorteners>=1.0.1,<2",
]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
